[package]
name = "rust_lib_hitomi_search_plus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.2.0"
tokio = { version = "1.0", features = ["full"] }
